# Generated by Django 3.0.8 on 2020-08-18 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('identify_code', models.CharField(max_length=500)),
                ('password_sha256', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('identify_code', models.CharField(max_length=500)),
                ('password_sha256', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('during_time', models.TimeField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.Bank')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.Client')),
            ],
        ),
    ]
