# Generated by Django 3.0.8 on 2020-09-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataManager', '0002_bill_client_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='ensure_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='bill',
            name='expiration',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
